version: '3'

services:
  crafty:
    container_name: crafty4
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "8000:8000" # HTTP
      - "8443:8443" # HTTPS
      - "8123:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - /config/crafty4/backups:/crafty/backups
      - /config/crafty4/logs:/crafty/logs
      - /config/crafty4/servers:/crafty/servers
      - /config/crafty4/config:/crafty/app/config
      - /config/crafty4/import:/crafty/import
    networks:
      mymacvlan:
        ipv4_address: 10.203.20.50

networks:
  mymacvlan:
    external:
      name: myMacVlan
