version: '3.7'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-M7AzpBQ9_G2WCQju_Umn #optional
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - /mnt/configs/plex:/config
      - /mnt/downloads:/downloads #optional
      - /mnt/media:/media #optional
      - /mnt/hidden:/hidden #optional
    networks:
      macvlan:
        ipv4_address: 10.203.20.42
    restart: unless-stopped

networks:
  macvlan:
    external: true
    name: myMacVlan
