version: '3.7'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-mBXqBsmCLFmK6kaz-r4d #optional
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - /config/plex:/config
      - /media/Films:/Films #optional
      - /media/TV:/TV #optional
      - /hidden:/hidden #optional
    networks:
      mymacvlan:
        ipv4_address: 10.203.20.42
    restart: unless-stopped

networks:
  mymacvlan:
    external:
      name: myMacVlan
