version: '3.7'

services:
  sonarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - /mnt/configs/radarr:/config
      - /mnt/downloads:/downloads #optional
      - /mnt/media:/media #optional

    networks:
      macvlan:
        ipv4_address: 10.203.20.41
    restart: unless-stopped

networks:
  macvlan:
    external: true
    name: myMacVlan
