version: '3.7'

services:
  sonarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/radarr/data:/config
      - /path/to/tvseries:/tv #optional
      - /path/to/downloadclient-downloads:/downloads #optional
    networks:
      mymacvlan:
        ipv4_address: 10.203.20.41
    restart: unless-stopped

networks:
  mymacvlan:
    external:
      name: myMacVlan
