version: '3.8'

services:
  rundeck:
    image: rundeck/rundeck:latest
    container_name: rundeck
    environment:
      - RUNDECK_GRAILS_URL=http://10.203.20.52:4440
      - RUNDECK_SERVER_ADDRESS=10.203.20.52
    volumes:
      - /config/rundeck/data:/home/rundeck/server/data
    networks:
      mymacvlan:
        ipv4_address: 10.203.20.52
    ports:
      - 4440:4440
    restart: unless-stopped

networks:
  mymacvlan:
    external:
      name: myMacVlan
