version: '3.8'
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/configs/sabnzbd:/config
      - /mnt/downloads:/downloads #optional
      - /mnt/media:/media #optional
      - /mnt/hidden:/hidden #optional
    networks:
      macvlan:
        ipv4_address: 10.203.20.44
    restart: unless-stopped

networks:
  macvlan:
    external: true
    name: myMacVlan
