version: '3.8'

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /config/sabnzbd:/config
      - /downloads:/downloads #optional
    networks:
      mymacvlan:
        ipv4_address: 10.203.20.44
    restart: unless-stopped

networks:
  mymacvlan:
    external:
      name: myMacVlan
