version: '3.7'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
    volumes:
      - /mnt/configs/sonarr:/config
      - /mnt/downloads:/downloads #optional
      - /mnt/media:/media #optional

    networks:
      macvlan:
        ipv4_address: 10.203.20.40
    restart: unless-stopped

networks:
  macvlan:
    external: true
    name: myMacVlan

      
