version: '3.7'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /config/sonarr:/config
      - /media/TV:/TV #optional
      - /downloads:/downloads #optional
    networks:
      mymacvlan:
        ipv4_address: 10.203.20.40
    restart: unless-stopped

networks:
  mymacvlan:
    external:
      name: myMacVlan
